########### For examples that have requested a particular configuration:

TAU_MAKEFILE_FORTRAN=$(TAUROOT)/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthread-adios2
TAU_MAKEFILE_MPI=$(TAUROOT)/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthread-adios2
TAU_MAKEFILE_MPI_FORTRAN=$(TAUROOT)/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthread-adios2
TAU_MAKEFILE_MPI_OPENMP=$(LAST_MAKEFILE)
TAU_MAKEFILE_OPARI=$(LAST_MAKEFILE)
TAU_MAKEFILE_PTHREAD=$(TAUROOT)/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthread-adios2
TAU_MAKEFILE_PAPI=$(TAUROOT)/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthread-adios2
TAU_MAKEFILE_PAPI_PTHREAD=$(TAUROOT)/ibm64linux/lib/Makefile.tau-papi-gnu-mpi-pthread-adios2
TAU_MAKEFILE_SPROC=$(LAST_MAKEFILE)
TAU_MAKEFILE_PDT=$(LAST_MAKEFILE)
TAU_MAKEFILE_PDT_MPI=$(LAST_MAKEFILE)
TAU_MAKEFILE_PDT_PTHREAD=$(LAST_MAKEFILE)
TAU_MAKEFILE_PDT_OPENMP=$(LAST_MAKEFILE)
TAU_MAKEFILE_PDT_OPARI=$(LAST_MAKEFILE)
TAU_MAKEFILE_PDT_FORTRAN=$(LAST_MAKEFILE)
