
export CODAR_CHEETAH_GROUP_WALLTIME="1860"
export CODAR_CHEETAH_GROUP_MAX_PROCS="10"

export CODAR_CHEETAH_SCHEDULER_ACCOUNT=""
# queue on PBS, partition on SLURM
export CODAR_CHEETAH_SCHEDULER_QUEUE=""
# SLURM specific options
export CODAR_CHEETAH_SCHEDULER_CONSTRAINT=""
export CODAR_CHEETAH_SCHEDULER_LICENSE=""

export CODAR_CHEETAH_CAMPAIGN_NAME="codar.cheetah.heat2d-simple"

export CODAR_CHEETAH_GROUP_NAME="small_scale"
export CODAR_CHEETAH_GROUP_NODES="3"
export CODAR_CHEETAH_GROUP_NODE_EXCLUSIVE="False"
export CODAR_CHEETAH_GROUP_PROCESSES_PER_NODE="4"
