"Usage: otf2-config [OPTION]... COMMAND\n"
"\n"
"Commands:\n"
"  --cflags     prints additional compiler flags. They already contain\n"
"               the include flags\n"
"  --cppflags   prints the include flags for the OTF2 headers\n"
"  --libs       prints the required libraries for linking\n"
"  --ldflags    prints the required linker flags\n"
"  --cc         prints the C compiler name\n"
"  --features <FEATURE-CATEGORY>\n"
"               prints available features selected by <FEATURE-CATEGORY>.\n"
"               Available feature categories:\n"
"                * substrates\n"
"                * compressions\n"
"                * targets\n"
"  --help       prints this usage information\n"
"\n"
"  --version    prints the version number of the OTF2 package and\n"
"  --otf2-revision\n"
"               prints the revision number of the OTF2 package\n"
"  --common-revision\n"
"               prints the revision number of the common package\n"
"  --interface-version\n"
"               prints the interface version number\n"
"  --pythonpath\n"
"               prints the python path for the OTF2 modules\n"
"\n"
"Options:\n"
"  --target <TARGET>\n"
"               displays the requested information for the given <TARGET>.\n"
"               On non-cross compiling systems, the 'backend' target is ignored.\n"
"  --backend    equivalent to '--target backend' (deprecated)\n"
"  --cuda       specifies that the required flags are for the CUDA compiler\n"
"               nvcc (deprecated)\n"
